apiVersion: v1
kind: Service
metadata:
  name: generic-prime-backend
  namespace: generic-prime
  labels:
    app: generic-prime-backend
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: generic-prime-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
